apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234 # Match your app's internal port
      nodePort: 30080  # You can access the app at http://localhost:30080
